USE board;

-- 1. Seed community users with stable credentials
INSERT INTO users (email, password, nickname, role, created_at, updated_at) VALUES
('loadtest1@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'sunny', 'USER', NOW(), NOW()),
('loadtest2@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'mina', 'USER', NOW(), NOW()),
('loadtest3@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'junho', 'USER', NOW(), NOW()),
('loadtest4@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'sofia', 'USER', NOW(), NOW()),
('loadtest-admin@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'mod', 'ADMIN', NOW(), NOW()),
('loadtest5@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'ariel', 'USER', NOW(), NOW()),
('loadtest6@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'dave', 'USER', NOW(), NOW()),
('loadtest7@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'chloe', 'USER', NOW(), NOW()),
('loadtest8@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'yujin', 'USER', NOW(), NOW()),
('loadtest9@example.com', '$2y$10$r8Wcsl7zV1i2la94TM3zjOxsYsRSXWLzvT32iKTODXk0Z/p/6A4p2', 'peter', 'USER', NOW(), NOW());

-- 2. Attach profile images to each user
INSERT INTO images (s3_key, user_id) VALUES
('cat.jpeg', (SELECT user_id FROM users WHERE email = 'loadtest1@example.com')),
('sunflower.jpeg', (SELECT user_id FROM users WHERE email = 'loadtest2@example.com')),
('person.jpg', (SELECT user_id FROM users WHERE email = 'loadtest3@example.com')),
('boardwalk.jpg', (SELECT user_id FROM users WHERE email = 'loadtest4@example.com')),
('flower.jpeg', (SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com')),
('cat.jpeg', (SELECT user_id FROM users WHERE email = 'loadtest5@example.com')),
('sunflower.jpeg', (SELECT user_id FROM users WHERE email = 'loadtest6@example.com')),
('person.jpg', (SELECT user_id FROM users WHERE email = 'loadtest7@example.com')),
('boardwalk.jpg', (SELECT user_id FROM users WHERE email = 'loadtest8@example.com')),
('flower.jpeg', (SELECT user_id FROM users WHERE email = 'loadtest9@example.com'));

-- 3. Pre-create post image metadata for deterministic IDs
INSERT INTO images (s3_key) VALUES
('cat.jpeg'),
('flower.jpeg'),
('person.jpg'),
('sunflower.jpeg'),
('boardwalk.jpg'),
('cat.jpeg'),
('flower.jpeg'),
('person.jpg'),
('sunflower.jpeg'),
('boardwalk.jpg'),
('cat.jpeg'),
('flower.jpeg'),
('person.jpg'),
('sunflower.jpeg'),
('boardwalk.jpg'),
('cat.jpeg'),
('flower.jpeg'),
('person.jpg'),
('sunflower.jpeg'),
('boardwalk.jpg'),
('cat.jpeg'),
('flower.jpeg'),
('person.jpg'),
('sunflower.jpeg'),
('boardwalk.jpg'),
('cat.jpeg'),
('flower.jpeg'),
('person.jpg'),
('sunflower.jpeg'),
('boardwalk.jpg');

-- 4. Seed posts with story-style content
INSERT INTO posts (title, contents, user_id, created_at, updated_at) VALUES
('주말 한강 피크닉 후기', '돗자리 깔고 라면 끓여 먹었는데 아직 밤에는 쌀쌀하더라고요. 노을이 너무 예뻐서 사진 잔뜩 찍었습니다.', (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
('새로 문 연 동네 빵집 가보신 분?', '문 앞에서 줄이 길길래 결국 크루아상만 사왔어요. 식감이 꽤 버터리했는데 다른 메뉴 추천 있으신가요?', (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), DATE_SUB(NOW(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
('중고 노트북 업그레이드 상담', 'SSD 256GB라 용량이 자꾸 부족해서요. 1TB로 바꾸면 체감이 클까요? 메모리는 16GB입니다.', (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
('퇴근 후 러닝 모임 합류 후기', '처음 달려봤는데 한강 코스 5km 괜찮네요. 페이스가 맞아서 다음 주도 참석하려고 합니다.', (SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
('베란다 텃밭에서 토마토가 잘 안 자라요', '햇볕은 오전에만 들어오는데 잎이 노래지고 있습니다. 흙을 새로 갈아줘야 할까요?', (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
('넷플릭스 다큐 추천 좀 해주세요', '퇴근하고 가볍게 볼 만한 다큐멘터리 찾고 있어요. 몰입감 있는 작품이면 좋겠습니다.', (SELECT user_id FROM users WHERE email = 'loadtest8@example.com'), DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
('캠핑 입문 장비 리스트 공유', '쉘터 대신 타프부터 시작하려고요. 체어, 테이블, 코펠까지 기본만 챙기면 될까요?', (SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
('고양이가 밤에 울어요 이유 있을까요?', '밥도 챙겨주고 놀이도 해줬는데 새벽에 꼭 깨워서 울어요. 분리불안일까요?', (SELECT user_id FROM users WHERE email = 'loadtest7@example.com'), DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
('회사 점심 도시락 메뉴 고민', '샐러드만 먹으니 금방 배가 고파서요. 전자레인지로 쉽게 데울 수 있는 메뉴 추천해주세요.', (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
('사진 동호회 첫 출사 다녀왔어요', '광화문 근처 골목길 찍었는데 색감이 생각보다 탁했어요. 후보정 팁 있으면 부탁드립니다.', (SELECT user_id FROM users WHERE email = 'loadtest9@example.com'), DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
('집에서 해먹는 크림 파스타 레시피', '양파, 베이컨, 우유로 간단히 만들었는데 농도가 자꾸 묽어지네요. 불 조절을 어떻게 해야 할까요?', (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
('미니멀 데스크 셋업 정리', '모니터암 설치하고 케이블을 다 숨겼습니다. 의자만 바꾸면 끝인데 브랜드 추천 있으신가요?', (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),
('비 오는 날 듣기 좋은 노래 리스트', '어쿠스틱 위주로 10곡 정도 모아봤어요. 추가로 더 감성적인 곡 있으면 알려주세요.', (SELECT user_id FROM users WHERE email = 'loadtest8@example.com'), DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
('부산 여행 코스 초안 피드백', '1박2일로 광안리-기장-해동용궁사 코스로 잡았는데 이동 동선이 괜찮을까요?', (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
('아침 루틴을 좀 바꿔봤습니다', '커피 대신 미숫가루 마시고 10분 스트레칭하니 확실히 덜 피곤하네요. 꾸준히 해보려 합니다.', (SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), NOW(), NOW());

-- 5. Provide PostCount rows for derived metrics
INSERT INTO counts (post_id, likes_cnt, cmt_cnt, view_cnt) VALUES
((SELECT post_id FROM posts WHERE title = '주말 한강 피크닉 후기'), 52, 5, 620),
((SELECT post_id FROM posts WHERE title = '새로 문 연 동네 빵집 가보신 분?'), 38, 4, 510),
((SELECT post_id FROM posts WHERE title = '중고 노트북 업그레이드 상담'), 31, 3, 440),
((SELECT post_id FROM posts WHERE title = '퇴근 후 러닝 모임 합류 후기'), 28, 4, 405),
((SELECT post_id FROM posts WHERE title = '베란다 텃밭에서 토마토가 잘 안 자라요'), 26, 3, 370),
((SELECT post_id FROM posts WHERE title = '넷플릭스 다큐 추천 좀 해주세요'), 24, 3, 350),
((SELECT post_id FROM posts WHERE title = '캠핑 입문 장비 리스트 공유'), 22, 4, 330),
((SELECT post_id FROM posts WHERE title = '고양이가 밤에 울어요 이유 있을까요?'), 20, 4, 315),
((SELECT post_id FROM posts WHERE title = '회사 점심 도시락 메뉴 고민'), 18, 3, 290),
((SELECT post_id FROM posts WHERE title = '사진 동호회 첫 출사 다녀왔어요'), 17, 4, 270),
((SELECT post_id FROM posts WHERE title = '집에서 해먹는 크림 파스타 레시피'), 16, 3, 250),
((SELECT post_id FROM posts WHERE title = '미니멀 데스크 셋업 정리'), 15, 3, 240),
((SELECT post_id FROM posts WHERE title = '비 오는 날 듣기 좋은 노래 리스트'), 14, 3, 230),
((SELECT post_id FROM posts WHERE title = '부산 여행 코스 초안 피드백'), 13, 3, 215),
((SELECT post_id FROM posts WHERE title = '아침 루틴을 좀 바꿔봤습니다'), 12, 2, 200);

-- 6. Simulate likes for deterministic liked-by-user logic
INSERT INTO user_like_posts (user_id, post_id, liked_at) VALUES
((SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), (SELECT post_id FROM posts WHERE title = '주말 한강 피크닉 후기'), DATE_SUB(NOW(), INTERVAL 45 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), (SELECT post_id FROM posts WHERE title = '주말 한강 피크닉 후기'), DATE_SUB(NOW(), INTERVAL 44 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), (SELECT post_id FROM posts WHERE title = '주말 한강 피크닉 후기'), DATE_SUB(NOW(), INTERVAL 43 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), (SELECT post_id FROM posts WHERE title = '새로 문 연 동네 빵집 가보신 분?'), DATE_SUB(NOW(), INTERVAL 50 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), (SELECT post_id FROM posts WHERE title = '새로 문 연 동네 빵집 가보신 분?'), DATE_SUB(NOW(), INTERVAL 49 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), (SELECT post_id FROM posts WHERE title = '중고 노트북 업그레이드 상담'), DATE_SUB(NOW(), INTERVAL 55 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), (SELECT post_id FROM posts WHERE title = '중고 노트북 업그레이드 상담'), DATE_SUB(NOW(), INTERVAL 54 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), (SELECT post_id FROM posts WHERE title = '퇴근 후 러닝 모임 합류 후기'), DATE_SUB(NOW(), INTERVAL 35 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest7@example.com'), (SELECT post_id FROM posts WHERE title = '퇴근 후 러닝 모임 합류 후기'), DATE_SUB(NOW(), INTERVAL 34 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), (SELECT post_id FROM posts WHERE title = '베란다 텃밭에서 토마토가 잘 안 자라요'), DATE_SUB(NOW(), INTERVAL 33 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest9@example.com'), (SELECT post_id FROM posts WHERE title = '베란다 텃밭에서 토마토가 잘 안 자라요'), DATE_SUB(NOW(), INTERVAL 32 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest8@example.com'), (SELECT post_id FROM posts WHERE title = '넷플릭스 다큐 추천 좀 해주세요'), DATE_SUB(NOW(), INTERVAL 31 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), (SELECT post_id FROM posts WHERE title = '넷플릭스 다큐 추천 좀 해주세요'), DATE_SUB(NOW(), INTERVAL 30 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), (SELECT post_id FROM posts WHERE title = '캠핑 입문 장비 리스트 공유'), DATE_SUB(NOW(), INTERVAL 29 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), (SELECT post_id FROM posts WHERE title = '캠핑 입문 장비 리스트 공유'), DATE_SUB(NOW(), INTERVAL 28 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest7@example.com'), (SELECT post_id FROM posts WHERE title = '고양이가 밤에 울어요 이유 있을까요?'), DATE_SUB(NOW(), INTERVAL 27 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest8@example.com'), (SELECT post_id FROM posts WHERE title = '고양이가 밤에 울어요 이유 있을까요?'), DATE_SUB(NOW(), INTERVAL 26 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), (SELECT post_id FROM posts WHERE title = '회사 점심 도시락 메뉴 고민'), DATE_SUB(NOW(), INTERVAL 25 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), (SELECT post_id FROM posts WHERE title = '사진 동호회 첫 출사 다녀왔어요'), DATE_SUB(NOW(), INTERVAL 24 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest9@example.com'), (SELECT post_id FROM posts WHERE title = '사진 동호회 첫 출사 다녀왔어요'), DATE_SUB(NOW(), INTERVAL 23 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), (SELECT post_id FROM posts WHERE title = '집에서 해먹는 크림 파스타 레시피'), DATE_SUB(NOW(), INTERVAL 22 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), (SELECT post_id FROM posts WHERE title = '미니멀 데스크 셋업 정리'), DATE_SUB(NOW(), INTERVAL 21 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), (SELECT post_id FROM posts WHERE title = '비 오는 날 듣기 좋은 노래 리스트'), DATE_SUB(NOW(), INTERVAL 20 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), (SELECT post_id FROM posts WHERE title = '부산 여행 코스 초안 피드백'), DATE_SUB(NOW(), INTERVAL 19 MINUTE)),
((SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), (SELECT post_id FROM posts WHERE title = '아침 루틴을 좀 바꿔봤습니다'), DATE_SUB(NOW(), INTERVAL 18 MINUTE));

-- 7. Link post images in deterministic order for slice responses
INSERT INTO post_images (post_id, image_id, orders) VALUES
((SELECT post_id FROM posts WHERE title = '주말 한강 피크닉 후기'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 0), 1),
((SELECT post_id FROM posts WHERE title = '주말 한강 피크닉 후기'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 1), 2),
((SELECT post_id FROM posts WHERE title = '새로 문 연 동네 빵집 가보신 분?'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 2), 1),
((SELECT post_id FROM posts WHERE title = '새로 문 연 동네 빵집 가보신 분?'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 3), 2),
((SELECT post_id FROM posts WHERE title = '중고 노트북 업그레이드 상담'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 4), 1),
((SELECT post_id FROM posts WHERE title = '중고 노트북 업그레이드 상담'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 5), 2),
((SELECT post_id FROM posts WHERE title = '퇴근 후 러닝 모임 합류 후기'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 6), 1),
((SELECT post_id FROM posts WHERE title = '퇴근 후 러닝 모임 합류 후기'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 7), 2),
((SELECT post_id FROM posts WHERE title = '베란다 텃밭에서 토마토가 잘 안 자라요'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 8), 1),
((SELECT post_id FROM posts WHERE title = '베란다 텃밭에서 토마토가 잘 안 자라요'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 9), 2),
((SELECT post_id FROM posts WHERE title = '넷플릭스 다큐 추천 좀 해주세요'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 10), 1),
((SELECT post_id FROM posts WHERE title = '넷플릭스 다큐 추천 좀 해주세요'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 11), 2),
((SELECT post_id FROM posts WHERE title = '캠핑 입문 장비 리스트 공유'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 12), 1),
((SELECT post_id FROM posts WHERE title = '캠핑 입문 장비 리스트 공유'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 13), 2),
((SELECT post_id FROM posts WHERE title = '고양이가 밤에 울어요 이유 있을까요?'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 14), 1),
((SELECT post_id FROM posts WHERE title = '고양이가 밤에 울어요 이유 있을까요?'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 15), 2),
((SELECT post_id FROM posts WHERE title = '회사 점심 도시락 메뉴 고민'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 16), 1),
((SELECT post_id FROM posts WHERE title = '회사 점심 도시락 메뉴 고민'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 17), 2),
((SELECT post_id FROM posts WHERE title = '사진 동호회 첫 출사 다녀왔어요'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 18), 1),
((SELECT post_id FROM posts WHERE title = '사진 동호회 첫 출사 다녀왔어요'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 19), 2),
((SELECT post_id FROM posts WHERE title = '집에서 해먹는 크림 파스타 레시피'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 20), 1),
((SELECT post_id FROM posts WHERE title = '집에서 해먹는 크림 파스타 레시피'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 21), 2),
((SELECT post_id FROM posts WHERE title = '미니멀 데스크 셋업 정리'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 22), 1),
((SELECT post_id FROM posts WHERE title = '미니멀 데스크 셋업 정리'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 23), 2),
((SELECT post_id FROM posts WHERE title = '비 오는 날 듣기 좋은 노래 리스트'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 24), 1),
((SELECT post_id FROM posts WHERE title = '비 오는 날 듣기 좋은 노래 리스트'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 25), 2),
((SELECT post_id FROM posts WHERE title = '부산 여행 코스 초안 피드백'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 26), 1),
((SELECT post_id FROM posts WHERE title = '부산 여행 코스 초안 피드백'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 27), 2),
((SELECT post_id FROM posts WHERE title = '아침 루틴을 좀 바꿔봤습니다'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 28), 1),
((SELECT post_id FROM posts WHERE title = '아침 루틴을 좀 바꿔봤습니다'), (SELECT image_id FROM images WHERE user_id IS NULL ORDER BY image_id LIMIT 1 OFFSET 29), 2);

-- 8. Prepare chat rooms to exercise websocket subscription flows
INSERT INTO chat_rooms (name, is_group_chat, created_at, updated_at) VALUES
('동네수다', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
('취미모임', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY));

-- 9. Register chat participants
INSERT INTO chat_participants (user_id, chat_room_id, created_at, updated_at) VALUES
((SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), NOW(), NOW()),
((SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), NOW(), NOW());

-- 10. Insert chat history so /chat/history queries always have rows
INSERT INTO chat_messages (contents, chat_room_id, user_id, created_at, updated_at) VALUES
('동네 근처 새로 열린 카페 가보신 분 있어요?', (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), DATE_SUB(NOW(), INTERVAL 90 MINUTE), DATE_SUB(NOW(), INTERVAL 90 MINUTE)),
('오늘 미세먼지 좀 있어요. 마스크 챙기세요!', (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), DATE_SUB(NOW(), INTERVAL 70 MINUTE), DATE_SUB(NOW(), INTERVAL 70 MINUTE)),
('엘리베이터 점검한다는 공지가 붙어 있네요.', (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), DATE_SUB(NOW(), INTERVAL 50 MINUTE), DATE_SUB(NOW(), INTERVAL 50 MINUTE)),
('오늘 저녁에 산책모임 있나요?', (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE)),
('주말에 플리마켓 나가볼까요?', (SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), DATE_SUB(NOW(), INTERVAL 15 MINUTE), DATE_SUB(NOW(), INTERVAL 15 MINUTE)),
('러닝크루에 관심 있는 분 계세요?', (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), DATE_SUB(NOW(), INTERVAL 80 MINUTE), DATE_SUB(NOW(), INTERVAL 80 MINUTE)),
('주말에 드로잉 클래스 함께 듣는 사람 모집해요.', (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), DATE_SUB(NOW(), INTERVAL 60 MINUTE), DATE_SUB(NOW(), INTERVAL 60 MINUTE)),
('자전거 타실 분 있으면 메시지 주세요.', (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), DATE_SUB(NOW(), INTERVAL 40 MINUTE), DATE_SUB(NOW(), INTERVAL 40 MINUTE)),
('모임 일정은 캘린더에 정리해둘게요.', (SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), DATE_SUB(NOW(), INTERVAL 25 MINUTE), DATE_SUB(NOW(), INTERVAL 25 MINUTE));

-- 11. Reflect read receipts so messageRead API has deterministic state
INSERT INTO read_status (chat_room_id, chat_message_id, user_id, is_read, created_at, updated_at) VALUES
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '동네 근처 새로 열린 카페 가보신 분 있어요?'), (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 89 MINUTE), DATE_SUB(NOW(), INTERVAL 89 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '동네 근처 새로 열린 카페 가보신 분 있어요?'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 88 MINUTE), DATE_SUB(NOW(), INTERVAL 88 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '동네 근처 새로 열린 카페 가보신 분 있어요?'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 87 MINUTE), DATE_SUB(NOW(), INTERVAL 87 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '동네 근처 새로 열린 카페 가보신 분 있어요?'), (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 86 MINUTE), DATE_SUB(NOW(), INTERVAL 86 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '동네 근처 새로 열린 카페 가보신 분 있어요?'), (SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 85 MINUTE), DATE_SUB(NOW(), INTERVAL 85 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 미세먼지 좀 있어요. 마스크 챙기세요!'), (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 69 MINUTE), DATE_SUB(NOW(), INTERVAL 69 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 미세먼지 좀 있어요. 마스크 챙기세요!'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 70 MINUTE), DATE_SUB(NOW(), INTERVAL 70 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 미세먼지 좀 있어요. 마스크 챙기세요!'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 68 MINUTE), DATE_SUB(NOW(), INTERVAL 68 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 미세먼지 좀 있어요. 마스크 챙기세요!'), (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 67 MINUTE), DATE_SUB(NOW(), INTERVAL 67 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 미세먼지 좀 있어요. 마스크 챙기세요!'), (SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 66 MINUTE), DATE_SUB(NOW(), INTERVAL 66 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '엘리베이터 점검한다는 공지가 붙어 있네요.'), (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 49 MINUTE), DATE_SUB(NOW(), INTERVAL 49 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '엘리베이터 점검한다는 공지가 붙어 있네요.'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 48 MINUTE), DATE_SUB(NOW(), INTERVAL 48 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '엘리베이터 점검한다는 공지가 붙어 있네요.'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 50 MINUTE), DATE_SUB(NOW(), INTERVAL 50 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '엘리베이터 점검한다는 공지가 붙어 있네요.'), (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 47 MINUTE), DATE_SUB(NOW(), INTERVAL 47 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '엘리베이터 점검한다는 공지가 붙어 있네요.'), (SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 46 MINUTE), DATE_SUB(NOW(), INTERVAL 46 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 저녁에 산책모임 있나요?'), (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 29 MINUTE), DATE_SUB(NOW(), INTERVAL 29 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 저녁에 산책모임 있나요?'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 28 MINUTE), DATE_SUB(NOW(), INTERVAL 28 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 저녁에 산책모임 있나요?'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 27 MINUTE), DATE_SUB(NOW(), INTERVAL 27 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 저녁에 산책모임 있나요?'), (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '오늘 저녁에 산책모임 있나요?'), (SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 26 MINUTE), DATE_SUB(NOW(), INTERVAL 26 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 플리마켓 나가볼까요?'), (SELECT user_id FROM users WHERE email = 'loadtest1@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 14 MINUTE), DATE_SUB(NOW(), INTERVAL 14 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 플리마켓 나가볼까요?'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 13 MINUTE), DATE_SUB(NOW(), INTERVAL 13 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 플리마켓 나가볼까요?'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 12 MINUTE), DATE_SUB(NOW(), INTERVAL 12 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 플리마켓 나가볼까요?'), (SELECT user_id FROM users WHERE email = 'loadtest4@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 11 MINUTE), DATE_SUB(NOW(), INTERVAL 11 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '동네수다'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 플리마켓 나가볼까요?'), (SELECT user_id FROM users WHERE email = 'loadtest5@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 15 MINUTE), DATE_SUB(NOW(), INTERVAL 15 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '러닝크루에 관심 있는 분 계세요?'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 80 MINUTE), DATE_SUB(NOW(), INTERVAL 80 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '러닝크루에 관심 있는 분 계세요?'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 79 MINUTE), DATE_SUB(NOW(), INTERVAL 79 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '러닝크루에 관심 있는 분 계세요?'), (SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 78 MINUTE), DATE_SUB(NOW(), INTERVAL 78 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '러닝크루에 관심 있는 분 계세요?'), (SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 77 MINUTE), DATE_SUB(NOW(), INTERVAL 77 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 드로잉 클래스 함께 듣는 사람 모집해요.'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 59 MINUTE), DATE_SUB(NOW(), INTERVAL 59 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 드로잉 클래스 함께 듣는 사람 모집해요.'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 60 MINUTE), DATE_SUB(NOW(), INTERVAL 60 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 드로잉 클래스 함께 듣는 사람 모집해요.'), (SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 58 MINUTE), DATE_SUB(NOW(), INTERVAL 58 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '주말에 드로잉 클래스 함께 듣는 사람 모집해요.'), (SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 57 MINUTE), DATE_SUB(NOW(), INTERVAL 57 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '자전거 타실 분 있으면 메시지 주세요.'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 39 MINUTE), DATE_SUB(NOW(), INTERVAL 39 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '자전거 타실 분 있으면 메시지 주세요.'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 38 MINUTE), DATE_SUB(NOW(), INTERVAL 38 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '자전거 타실 분 있으면 메시지 주세요.'), (SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 40 MINUTE), DATE_SUB(NOW(), INTERVAL 40 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '자전거 타실 분 있으면 메시지 주세요.'), (SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 37 MINUTE), DATE_SUB(NOW(), INTERVAL 37 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '모임 일정은 캘린더에 정리해둘게요.'), (SELECT user_id FROM users WHERE email = 'loadtest2@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 24 MINUTE), DATE_SUB(NOW(), INTERVAL 24 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '모임 일정은 캘린더에 정리해둘게요.'), (SELECT user_id FROM users WHERE email = 'loadtest3@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 23 MINUTE), DATE_SUB(NOW(), INTERVAL 23 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '모임 일정은 캘린더에 정리해둘게요.'), (SELECT user_id FROM users WHERE email = 'loadtest6@example.com'), FALSE, DATE_SUB(NOW(), INTERVAL 22 MINUTE), DATE_SUB(NOW(), INTERVAL 22 MINUTE)),
((SELECT chat_room_id FROM chat_rooms WHERE name = '취미모임'), (SELECT chat_message_id FROM chat_messages WHERE contents = '모임 일정은 캘린더에 정리해둘게요.'), (SELECT user_id FROM users WHERE email = 'loadtest-admin@example.com'), TRUE, DATE_SUB(NOW(), INTERVAL 25 MINUTE), DATE_SUB(NOW(), INTERVAL 25 MINUTE));
